defaults:
  - behavior_ppo_openpi_pi05

hydra:
  searchpath:
    - file://${oc.env:EMBODIED_PATH}/config/

cluster:
  num_nodes: 1
  component_placement:
    rollout: all
    env: all
    actor: all

runner:
  logger:
    experiment_name: "behavior_ppo_openpi05_eval"
  only_eval: True

algorithm:
  eval_rollout_epoch: 2
  reward_coef: 2048

rollout:
  model:
    model_path: /mnt/public/tgy/ckpts/pi05-turning_on_radio-sft-pytorch

env:
  group_name: "EnvGroup"

  train:
    total_num_envs: 8
    max_episode_steps: 2048
    max_steps_per_rollout_epoch: 2048
    reward_coef: ${algorithm.reward_coef}
    video_cfg:
      save_video: True
      video_base_dir: ${runner.logger.log_path}/video/train
    # uncomment to use instance id
    # omni_config:
    #   task:
    #     activity_instance_dir: /path/to/BEHAVIOR-1K-datasets/2025-challenge-task-instances/scenes/house_double_floor_lower/json/house_double_floor_lower_task_turning_on_radio_instances
    #     instance_file_format: tro_state
    #     instance_resample_mode: offline
    #     online_object_sampling: False
    #     use_presampled_robot_pose: True
  eval:
    total_num_envs: 8
    max_episode_steps: 4096
    max_steps_per_rollout_epoch: 4096
    video_cfg:
      save_video: True
      video_base_dir: ${runner.logger.log_path}/video/eval
    skip_intermediate_obs_in_chunk: False  # set to False to save full video
    omni_config:
      env:
        action_frequency: 30
        physics_frequency: 120
        rendering_frequency: 30
      task:
        activity_instance_dir: ${oc.env:OMNIGIBSON_DATA_PATH}/2025-challenge-task-instances/scenes/house_double_floor_lower/json/house_double_floor_lower_task_turning_on_radio_instances
        activity_instance_id: [242, 295, 211, 203, 109, 181, 197, 187, 214, 139]
        instance_file_format: tro_state
        instance_resample_mode: offline
        online_object_sampling: False
        use_presampled_robot_pose: True
        reward_config:
          reward_mode: task
          task_specific_reward_name: turning_on_radio

actor:
  model:
    model_path: ${rollout.model.model_path}
    openpi:
      noise_level: 0.0
    openpi_data:
      assets:
        assets_dir: ${actor.model.model_path}
        asset_id: assets/behavior-1k/2025-challenge-demos
