model_type: "openpi"

# Model path - should be set in specific config files
model_path: "/path/to/model/openpi"

precision: null # for openpi, precision is null, please do not change this value

# Action and chunk settings
num_action_chunks: 10
action_dim: 7

# LoRA settings
is_lora: False
lora_rank: 32

# Training settings
use_proprio: True
num_steps: 5
add_value_head: False

# openpi specific parameters
openpi:
  config_name: "pi05_libero"
  num_images_in_input: 2
  noise_level: 0.5
  action_chunk: ${actor.model.num_action_chunks}
  num_steps: ${actor.model.num_steps}
  train_expert_only: True
  action_env_dim: ${actor.model.action_dim}
  noise_method: "flow_sde"
  add_value_head: ${actor.model.add_value_head}
  value_after_vlm: False
  value_vlm_mode: "mean_token"
  detach_critic_input: null
  use_privileged_teacher_obs: False
  privileged_teacher_injection: "state_projection"
  privileged_teacher_obs_dim: 226
  privileged_teacher_state_dim: 23
  privileged_teacher_num_tokens: 5
  privileged_teacher_token_hidden_dim: 256

  # DSRL specific configurations (disabled by default)
  use_dsrl: False
  dsrl_state_dim: 8
  dsrl_action_noise_dim: 32
  dsrl_num_q_heads: 10
  dsrl_agg_q: "mean"
  dsrl_image_latent_dim: 64
  dsrl_state_latent_dim: 64
  dsrl_hidden_dims: [128, 128, 128]
